# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55f105c1fcca516c207da619532610fe93155ee44b737020563508afcc13a225bc4d948535b83ffbc43ce57ee5abbe7f70afc6333f77f5ddc6d497c016759f6a

test:
  secret_key_base: 1ff2f7b0f0543cc1082c0b4b05351e2ceb5444601cf779ea794e715448cb012c241bbf7a3d7d01e8ce48896ce548234142fd477b551d712ab662c5fc0afee362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
